{
 "title": "config-sync",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(system_cpu_usage{namespace=~\".+\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=~\"$namespace\", app_kubernetes_io_component=\"config-sync\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=~\"$namespace\", app_kubernetes_io_component=\"config-sync\"}*1000"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_free_bytes{app_kubernetes_io_component=\"config-sync\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "disk_total_bytes{app_kubernetes_io_component=\"config-sync\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_component=\"config-sync\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_component=\"config-sync\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_component=\"config-sync\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_component=\"config-sync\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(sync_seconds_sum{app_kubernetes_io_component=\"config-sync\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(sync_blobs_seconds_sum{app_kubernetes_io_component=\"config-sync\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{uri=\"/actuator/health\", status=\"200\", app_kubernetes_io_component=\"config-sync\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(http_server_requests_seconds_count{uri=\"/actuator/health\", status!=\"200\", app_kubernetes_io_component=\"config-sync\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{app_kubernetes_io_component=\"config-sync\", namespace=\"$namespace\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{app_kubernetes_io_component=\"config-sync\", namespace=\"$namespace\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{app_kubernetes_io_component=\"config-sync\", namespace=\"$namespace\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", app_kubernetes_io_component=\"config-sync\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\", app_kubernetes_io_component=\"config-sync\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\", app_kubernetes_io_component=\"config-sync\"})",
     "legendFormat": "max"
    }
   ]
  }
 ]
}