{
 "title": "Customer Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Fusion Installation",
    "query": "label_values(http_server_requests_seconds_count{namespace=~\".+\"},namespace)"
   },
   {
    "name": "stageId",
    "label": "Stage Id",
    "query": "label_values(query_stage_outcome_total{namespace=~\"$namespace\",stageId=~\".+\",pipelineId!~\"_lw_tmp_.*\"},stageId)"
   },
   {
    "name": "queryPipelineId",
    "label": "Query Pipeline",
    "query": "label_values(query_stage_outcome_total{namespace=~\"$namespace\",pipelineId=~\".+\",pipelineId!~\"_lw_tmp_.*\"},pipelineId)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(query_stage_outcome_total{namespace=~\"$namespace\",pod=~\".+\",pipelineId!~\"_lw_tmp_.*\"},pod)"
   },
   {
    "name": "indexPipelineId",
    "label": "Indexing Pipeline",
    "query": "label_values(indexing_docs_in_total{namespace=~\"$namespace\"},pipelineId)"
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "label_values(query_stage_outcome_total{namespace=~\"$namespace\",pipelineId=~\".+\",pipelineId!~\"_lw_tmp_.*\"},pipelineId)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fusion Gateway RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{namespace=~\"$namespace\",routeId=\"apps_qp\",app_kubernetes_io_component=\"api-gateway\"}[1m]))",
     "legendFormat": "Query Route RPS"
    },
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{namespace=~\"$namespace\",app_kubernetes_io_component=\"api-gateway\"}[1m]))",
     "legendFormat": "Global RPS"
    }
   ]
  },
  {
   "title": "Gateway Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{namespace=~\"$namespace\",outcome=\"SERVER_ERROR\",routeId=\"apps_qp\"}[1m]))",
     "legendFormat": "Query Error Rate"
    },
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{namespace=~\"$namespace\",outcome=\"SERVER_ERROR\",routeId=~\"(indexing|indexing_apps)\"}[1m]))",
     "legendFormat": "Indexing Error Rate"
    }
   ]
  },
  {
   "title": "Query RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app_kubernetes_io_component=\"query-pipeline\",uri=\"/query/{id}\"}[1m]))",
     "legendFormat": "Query Pipeline Requests Per Second"
    }
   ]
  },
  {
   "title": "Indexing RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app_kubernetes_io_component=\"fusion-indexing\",uri=~\"/api/v1/index-pipelines/(.*)\",method=\"POST\"}[1m]))",
     "legendFormat": "Indexing Requests Per Second"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Query Pipeline RPS (with outcomes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (outcome)(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",app_kubernetes_io_component=\"query-pipeline\",uri=~\"/query/{id}\"}[1m]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Query Pipeline RPS By Pipeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pipelineId)(rate(pipeline_execution_duration_secs_count{namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m]))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p95 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p99 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p50 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p75 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "Indexing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexing Service RPS (non-GET)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app_kubernetes_io_component=\"fusion-indexing\",method!=\"GET\"}[1m]))"
      }
     ]
    },
    {
     "title": "Document Index Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum by(pipelineId)(rate(indexing_docs_in_total{namespace=~\"$namespace\",app_kubernetes_io_component=\"fusion-indexing\",pipelineId=~\"$indexPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m]))\n",
       "legendFormat": "{{pipelineId}}"
      }
     ]
    },
    {
     "title": "p99 Index Pipeline Execution Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(pipelineId, le)(rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$indexPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
       "legendFormat": "{{pipelineId}}"
      }
     ]
    },
    {
     "title": "p95 Index Pipeline Execution Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(pipelineId, le)(rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$indexPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
       "legendFormat": "{{pipelineId}}"
      }
     ]
    },
    {
     "title": "p75 Index Pipeline Execution Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum by(pipelineId, le)(rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$indexPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
       "legendFormat": "{{pipelineId}}"
      }
     ]
    },
    {
     "title": "p50 Index Pipeline Execution Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(pipelineId, le)(rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$indexPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
       "legendFormat": "{{pipelineId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Stages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Stage p99 Execution Times (histogram)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(stageId, pipelineId, le) (rate(query_stage_time_secs_bucket{namespace=~\"$namespace\", pod=~\"$pod\", pipelineId=~\"$queryPipelineId\", pipelineId!~\"_lw_tmp_.*\", stageId=~\"$stageId\"}[1m])))",
       "legendFormat": "{{pipelineId}} {{stageId}}"
      }
     ]
    },
    {
     "title": "Query Stage p95 Execution Times (histogram)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(stageId, pipelineId, le) (rate(query_stage_time_secs_bucket{namespace=~\"$namespace\", pod=~\"$pod\", pipelineId=~\"$queryPipelineId\", pipelineId!~\"_lw_tmp_.*\", stageId=~\"$stageId\"}[1m])))",
       "legendFormat": "{{pipelineId}} {{stageId}}"
      }
     ]
    },
    {
     "title": "Query Stage p75 Execution Times (histogram)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum by(stageId, pipelineId, le) (rate(query_stage_time_secs_bucket{namespace=~\"$namespace\", pod=~\"$pod\", pipelineId=~\"$queryPipelineId\", pipelineId!~\"_lw_tmp_.*\", stageId=~\"$stageId\"}[1m])))",
       "legendFormat": "{{pipelineId}} {{stageId}}"
      }
     ]
    },
    {
     "title": "Query Stage p50 Execution Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(stageId, pipelineId, le) (rate(query_stage_time_secs_bucket{namespace=~\"$namespace\", pod=~\"$pod\", pipelineId=~\"$queryPipelineId\", pipelineId!~\"_lw_tmp_.*\", stageId=~\"$stageId\"}[1m])))",
       "legendFormat": "{{pipelineId}} {{stageId}}"
      }
     ]
    },
    {
     "title": "Query Stage Execution Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(query_stage_outcome_total{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}) by (error, pipelineId, stageType)",
       "legendFormat": "{{pipelineId}} {{stageType}} (error {{error}})"
      }
     ]
    },
    {
     "title": "Stages per minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(query_stage_outcome_total{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])) by (error, pipelineId, stageType)",
       "legendFormat": "{{pipelineId}} {{stageType}} runs per minute"
      }
     ]
    }
   ]
  }
 ]
}