{
 "title": "Report Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Fusion Installation",
    "query": "label_values(http_server_requests_seconds_count{kubernetes_namespace=~\".+\"},kubernetes_namespace)"
   },
   {
    "name": "queryPipelineId",
    "label": "Query Pipeline",
    "query": "label_values(query_stage_outcome_total{kubernetes_namespace=~\"$namespace\",pipelineId=~\".+\"},pipelineId)"
   },
   {
    "name": "indexPipelineId",
    "label": "Indexing Pipeline",
    "query": "label_values(indexing_docs_in_total{kubernetes_namespace=~\"$namespace\"},pipelineId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Fusion Gateway RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_requests_seconds_count{kubernetes_namespace=~\"$namespace\",routeId=\"apps_qp\",app_kubernetes_io_component=\"api-gateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "Query Pipeline RPS (with outcomes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (outcome)(rate(http_server_requests_seconds_count{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_component=\"query-pipeline\",uri=~\"/query/{id}\"}[1m]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pipeline RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pipelineId)(rate(pipeline_execution_duration_secs_count{kubernetes_namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\"}[1m]))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "Avg Pipeline RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sum by(pipelineId)(rate(pipeline_execution_duration_secs_count{kubernetes_namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\"}[1m])) >0 )",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p99 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "Avg p99 Query Pipeline Execution Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\"}[1m]))) > 0)",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p95 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "Avg p95 Query Pipeline Execution Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\"}[1m]))) > 0)",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p75 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "Avg p75 Query Pipeline Execution Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.75, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\"}[1m]))) > 0)",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p50 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "Avg p50 Query Pipeline Execution Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.50, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$namespace\",pipelineId=~\"$queryPipelineId\"}[1m]))) > 0)",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  }
 ]
}